export enum WeatherCodes {
  Clear_Sky = 0,
  Mainly_Clear = 1,
  Partly_Cloudy = 2,
  Overcast = 3,
  Fog = 45,
  Depositing_Rime_Fog = 48,
  Drizzle_Light = 51,
  Drizle_Moderate = 53,
  Drizzle_Dense = 55,
  Freezing_Drizzle_Light = 56,
  Freezing_Drizzle_Dense = 57,
  Rain_Slight = 61,
  Rain_Moderate = 63,
  Rain_Heavy = 65,
  Freezing_Rain_Light = 66,
  Freezing_Rain_heavy = 67,
  Snow_Fall_Slight = 71,
  Snow_Fall_Moderate = 73,
  Snow_Fall_Heavy = 75,
  Snow_Grains = 77,
  Rain_Showers_Slight = 80,
  Rain_Showers_Moderate = 81,
  Rain_Showers_Violent = 82,
  Snow_Showers_Slight = 85,
  Snow_Showers_Heavy = 86
}
